In [1]:
import numpy as np


In [2]:
np.array(range(100)).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [3]:
np.full((10,10), 3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [4]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [5]:
np.linspace(0,10,4,dtype='int')

array([ 0,  3,  6, 10])

In [6]:
np.random.normal(0,1, (3,3))

array([[-1.60246322,  0.27240124,  0.68641479],
       [ 0.25099205,  0.49053026, -0.6034118 ],
       [ 1.28886448, -0.15924469,  0.22717889]])

In [7]:
np.random.randint(0, 10 , (3,3), dtype=np.int16)

array([[2, 5, 4],
       [9, 6, 8],
       [3, 4, 4]], dtype=int16)

In [8]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.normal(0, 1, size=(4,5))

array([[-0.86114822, -0.18135502,  0.3092563 ,  0.5835395 , -1.70248659],
       [-0.6405794 , -0.40639349, -1.72494118, -1.59832368,  1.26149721],
       [-0.5807007 , -0.06976766, -0.22455083, -1.6261975 , -0.07168798],
       [ 0.08603054, -1.36993105, -1.01037106, -0.94365241,  0.92010812]])

In [27]:
array_empty = np.empty(6)

In [28]:
id(array_empty)

136560731293904

In [10]:
np.int16

numpy.int16

In [11]:
arr_line = np.arange(0,100).reshape(10,10)
arr_line[1][-1] = 90.32
arr_line[:, 3:4].copy()


array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83],
       [93]])

In [12]:
np.split(arr_line, [3, 5])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 90],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [13]:
np.savetxt('my_arr.txt', arr_line, delimiter=',')

In [14]:
arr_line[arr_line > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 90, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
       96, 97, 98, 99])

In [15]:
np.random.seed(10)
new = np.random.randint(-100, 100, (10,10))


In [16]:
%timeit abs(new)

391 ns ± 5.87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
%timeit np.absolute(new)    


398 ns ± 4.42 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
%timeit np.power(arr_line, 2)

1.26 μs ± 136 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%timeit arr_line ** 2

501 ns ± 87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:

np.multiply.reduce(arr_line)

array([                 0,    478015854767451,   1242688846823424,
         2394832584543399,   4060162871525376,   6393838623046875,
         9585618768101376,  13865696119905399,  19511273389031424,
       127202925241001610])

In [21]:
np.random.RandomState(42)

arr = np.random.randint(0, 100, (10, 10))\

arr


array([[23,  3, 29, 16, 84, 82, 14, 51, 79, 17],
       [50, 53, 25, 48, 17, 32, 81, 80, 41, 90],
       [12, 30, 81, 17, 16,  0, 31, 73, 64, 38],
       [22, 96, 66, 67, 62, 95, 99, 27, 82, 62],
       [77, 48, 93, 75, 86, 37, 11, 21, 33, 95],
       [43, 88, 96, 73, 40, 43, 90, 71,  8, 85],
       [72, 28, 30, 89, 25, 78, 81, 85, 62, 13],
       [41, 33,  4, 87, 94, 28, 39, 91,  9,  7],
       [22, 32,  3,  9, 52, 76, 68, 30, 70, 74],
       [30,  9,  2, 65, 13, 75, 52,  5, 93, 84]])

In [22]:
sample = np.random.choice(arr.ravel(), 20, replace=False)

In [23]:
sample

array([51, 96, 25, 29, 21, 75,  0, 99, 31, 76, 79, 22, 87, 22, 32,  4, 40,
       52, 48, 88])

In [24]:
"hello"

'hello'

In [25]:



def print_name(name, **kwargs):
    print(name, name*2)

    for key, value in kwargs.items():
        print(key, value)




if __name__ == "__main__":
    print_name('Love', love="hahha", distubs="kind of weird")



Love LoveLove
love hahha
distubs kind of weird


In [32]:
y = np.ones(12)
x = np.ones(12)
# z = np.ones_like(y)
print("id(y)", id(y))
y = x + y
print('id(y)', id(y))

id(y) 136560363655152
id(y) 136560026036112


In [34]:
y

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [37]:
y.item()

ValueError: can only convert an array of size 1 to a Python scalar